### ISSUE TITLE
增强 demo

### ISSUE THREAD

**Issue by warmhug** [sorrycc/dva#2]
例如在`products/vote/success`的action成功后，触发一个和`ProductList`不同的组件的action（即另一个model的变化），包括相应 state 的变化。

**Comment by sorrycc** [comment]
为啥要做这一点? 确保 model 之间联动没有问题吗? redux 和 react-redux 会保证这一点的。

**Comment by warmhug** [comment]
一个 model 里能触发另一个 model 里的 action，也是可以的吧？

**Comment by sorrycc** [comment]
背后就是 redux，都可以的。
